services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sca-app
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=sca-redis:6379
      - MYSQL_HOST=sca-mysql
    restart: unless-stopped
    command: [ "./scripts/wait-for-it.sh", "sca-mysql:3306", "--", "./app", "-config", "configs/stub.toml" ]

  database:
    image: mysql:8.0
    container_name: sca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: sca
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2
    container_name: sca-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
